services:

  # PostgreSQL
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - upi-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 10


  # Redis
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    networks:
      - upi-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped

    environment:

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      # Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      # JWT
      JWT_SECRET: ${JWT_SECRET}

      # Google OAuth2
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    networks:
      - upi-network


  # Bank Service
  bank-service:
    build: ./bank-service
    container_name: bank-service
    restart: unless-stopped

    environment:

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - upi-network


  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: unless-stopped

    environment:

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      # Gmail
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - upi-network


  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped

    environment:
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8080:8080"

    depends_on:
      - user-service
      - bank-service
      - notification-service

    networks:
      - upi-network


  # PayUpi Frontend
  payupi-frontend:
    build: ./payupi-frontend
    container_name: payupi-frontend
    restart: unless-stopped

    ports:
      - "4200:80"

    depends_on:
      - api-gateway

    networks:
      - upi-network


# Volumes
volumes:
  postgres_data:


# Networks
networks:
  upi-network:
    driver: bridge