services:


  # PostgreSQL

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - upi-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 10



  # Redis

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    networks:
      - upi-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5



  # User Service

  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped

    ports:
      - "8081:8081"

    environment:

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      # Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      # JWT
      JWT_SECRET: ${JWT_SECRET}

      # Google OAuth2
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    networks:
      - upi-network



# Volumes

volumes:
  postgres_data:



# Networks

networks:
  upi-network:
    driver: bridge