# Server
server.port=8080

# Application Name
spring.application.name=api-gateway

# ==========================
# Gateway MVC Routes
# ==========================

spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=lb://user-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.mvc.routes[1].id=bank-service
spring.cloud.gateway.mvc.routes[1].uri=lb://Bank-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/bank/**

spring.cloud.gateway.mvc.routes[2].id=notification-service
spring.cloud.gateway.mvc.routes[2].uri=lb://notification-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/notifications/**

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG

#Eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka               for localhost
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka