# ==========================
# Server
# ==========================
server:
  port: 8080

# ==========================
# Application
# ==========================
spring:
  application:
    name: api-gateway

  # ==========================
  # Gateway MVC Routes
  # ==========================
  cloud:
    gateway:
      server:
        webmvc:
          routes:

            # User Service
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/auth/**

            - id: user-oauth2
              uri: http://user-service:8081
              predicates:
                - Path=/oauth2/**

            - id: user-oauth2-login
              uri: http://user-service:8081
              predicates:
                - Path=/login/**

            # Bank Service
            - id: bank-service
              uri: http://bank-service:8083
              predicates:
                - Path=/bank/**

            # Notification Service
            - id: notification-service
              uri: http://notification-service:8082
              predicates:
                - Path=/notifications/**

            # Transaction Service
            - id: transaction-service
              uri: http://transaction-service:8084
              predicates:
                - Path=/transactions/**

# ==========================
# JWT
# ==========================
jwt:
  secret: ${JWT_SECRET}


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG